<?php
use Drupal\Component\Utility\Crypt;

/**
 *
 * @file
 * Primary module hooks for habeuk utilitaire module.
 */

// https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/group/entity_crud/10

/**
 * Implements hook_form_alter().
 */
function habeuk_utilitaire_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('habeuk_utilitaire.settings')->getRawData();
  $config['time_to_wait'] = (int) $config['time_to_wait'];
  if (!empty($config['enable']) && $config['time_to_wait'] > 0 && \Drupal::currentUser()->isAnonymous()) {
    /**
     *
     * @var \Symfony\Component\HttpFoundation\Session\Session $session
     */
    $session = \Drupal::service('session');
    $key = 'habeuk_utilitaire_validate_form' . $form_id;
    if (!$session->has($key)) {
      $control = [
        'time' => time(),
        'try' => 0,
        'time_to_wait' => $config['time_to_wait']
      ];
      $session->set($key, $control);
    }
    else {
      $control = $session->get($key);
      $control['try']++;
      $session->set($key, $control);
    }
    $form_state->set('time_variable', $control['time']);
    $form_state->set('user_force_try', $control['try']);
    $form_state->set('habeuk_utilitaire_key', $key);
    $form['#validate'][] = '_habeuk_utilitaire_form_validate_time';
  }
}

function _habeuk_utilitaire_form_validate_time($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $time = $form_state->get('time_variable');
  $user_force_try = $form_state->get('user_force_try');
  $time_to_wait = $form_state->get('time_to_wait') > 0 ? $form_state->get('time_to_wait') : 3;
  if ($user_force_try) {
    $time_to_wait = $user_force_try * $time_to_wait;
  }
  $result = time() - ($time + $time_to_wait);
  if ($result <= 0) {
    $form_state->setErrorByName('', t('You are submitting the form too quickly. Please wait a :time_to_wait seconds.', [
      ':time_to_wait' => $time_to_wait
    ]));
    \Drupal::logger('habeuk_utilitaire')->error('Form sumitted protect. User is submitting the form too quickly.');
  }
  else {
    /**
     *
     * @var \Symfony\Component\HttpFoundation\Session\Session $session
     */
    $session = \Drupal::service('session');
    $key = $form_state->get('habeuk_utilitaire_key');
    $session->remove($key);
  }
}

/**
 *
 * @param array $fields
 * @param array $context
 */
function habeuk_utilitaire_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['entity_type'] == 'paragraph') {
    $fields['id'] = [
      'type' => 'field',
      'label' => t('ID'),
      'weight' => 0
    ];
    $fields['callback_layout_edit'] = [
      'type' => 'callback',
      'label' => t('Edit config'),
      'callback' => '\Drupal\habeuk_utilitaire\HabeukUtilitaire::getRouteToedit',
      'weight' => 10
    ];
  }
  elseif ($context['entity_type'] == 'block_content') {
    $fields['id'] = [
      'type' => 'field',
      'label' => t('ID'),
      'weight' => 0
    ];
    $fields['type'] = [
      'type' => 'field',
      'label' => 'Type',
      'weight' => 0
    ];
  }
  elseif ($context['entity_type'] == 'node') {
    $fields['nid'] = [
      'type' => 'field',
      'label' => t('ID'),
      'weight' => 0
    ];
    $fields['type'] = [
      'type' => 'field',
      'label' => 'Type',
      'weight' => 0
    ];
    $fields['callback_layout_url'] = [
      'type' => 'callback',
      'label' => t('edition externe'),
      'callback' => '\Drupal\habeuk_utilitaire\HabeukUtilitaire::manageNode',
      'weight' => 10
    ];
  }
}

/**
 * implement hook_theme
 */
function habeuk_utilitaire_theme($existing, $type, $theme, $path) {
  return [
    'habeuk_utilitaire_render_rx' => [
      'variables' => [
        'icone' => NULL,
        'label' => NULL,
        'attributes' => [],
        'attributes_icone' => [],
        'attributes_label' => []
      ]
    ],
    'habeuk_utilitaire_render_rxs' => [
      'variables' => [
        'items' => [],
        'attributes' => []
      ]
    ],
    'habeuk_utilitaire_backlink' => [
      'variables' => [
        'link' => [],
        'attributes' => [],
        'icone' => null
      ]
    ]
  ];
}



