# Schema for the configuration files of the habeuk utilitaire module.
habeuk_utilitaire.settings:
  type: config_object
  label: 'habeuk utilitaire settings'
  mapping:
    example:
      type: string
      label: 'Example'

block.settings.habeuk_utilitaire_sharerxs:
  type: block_settings
  label: 'ShareRxs block'
  mapping:
    entity:
      type: string
      label: Entity
    items_raw:
      type: mapping
      label: items_raw
